### ISSUE TITLE
librgblibffi.so: No such file or directory

### ISSUE THREAD

**Issue by 21sat** [RGB-Tools/rgb-lib-python#1]
Hi, I was trying to test the library but I get an error after running ./generate.sh 
Here the log:

> Generating librgblibffi.so...
>     Finished dev [unoptimized + debuginfo] target(s) in 0.53s
> cp: ./rgb-lib/rgb-lib-ffi/target/debug/librgblibffi.so: No such file or directory
>

**Comment by nicbus** [comment]
Hi, tried to reproduce the issue by cloning and building a fresh copy in docker:

1. start a debian container:
    ```shell
    docker run --rm -it debian:stable bash
    ```
2. inside the container, generate rgb-lib python bindings:
    ```shell
    apt update
    apt install -y build-essential curl git libssl-dev pkg-config
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  # <enter> to Proceed with installation
    source "$HOME/.cargo/env"
    git clone https://github.com/RGB-Tools/rgb-lib-python
    cd rgb-lib-python/
    git submodule update --init
    ./generate.sh
    ```

This produces the expected result:
```
Generating librgblibffi.so...
    Updating [...]
  Downloaded [...]
    Compiling [...]
    Finished dev [unoptimized + debuginfo] target(s) in 2.21s
Generating rgb_lib.py...
    Compiling [...]
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `rgb-lib/rgb-lib-ffi/target/debug/rgb-lib-ffi-bindgen --language python --udl-file ./rgb-lib/rgb-lib-ffi/src/rgb-lib.udl`
Input UDL file is "./rgb-lib/rgb-lib-ffi/src/rgb-lib.udl"
Chosen language is python
Output directory is "/rgb-lib-python/rgb_lib/_rgb_lib/"
```

Can you please confirm building in docker works for you? Please also provide more info on your setup (OS, rust version, etc.) so we can better understand what could be going wrong for you.

**Comment by 21sat** [comment]
Hi thanks for your response. In docker I had no problem to build the library. Can a PR with a Dockerfile be useful? 
Probably the problem was due to some library on my pc, in any case macOS 12.X.X and cargo 1.64.0

**Comment by nicbus** [comment]
we already had a Dockerfile so we cleaned it up and used it to add support for building in docker. @21sat  feel free to test it and post your feedback
